### ISSUE TITLE
Content-store indexation

### ISSUE THREAD

**Issue by tltran-legion** [legion-labs/legion#1523]
## Summary

Add support for data indexation in the content-store library.

## Current State

The current content-store implementation makes very little assumptions about the nature of the data: it supports chunking it and dispatching it to an appropriate storage, and that's it. There is no concept of file names, file types or hierarchy between the blobs.

The goal is this task is to change that.

All the data we deal with is immutable. This offers several caching optimization but it also means that any index on that data can be immutable as well: as the data never changes, its organization doesn't either. This makes it possible to actually store such data indexes in the content-store itself as well.

The task proposes to implement a distributed tree system where tree nodes act as virtual folders and leaf nodes point to resources. Here is an exemple of such a tree that indexes resources by their *hexadecimal identifier*:

```
root/
├─ a0/
│  ├─ d3/
│  │  ├─ g6
│  ├─ e4/
│  │  ├─ h7
│  │  ├─ i8
├─ c2/
│  ├─ f5/
│  │  ├─ l1
├─ b1/
│  ├─ j9k0
```

In this example, you can distinguish several blobs whose identifiers are:

```
a0d3g6
a0e4h7
a0e4i8
c2f5i1
b1j9k0
```

Note how blobs whose identifiers have the same prefix are bundled together: this means that searching for the resource with id `a0e4h7` will be done by first loading the `root` tree node, then the node `a0`, the node `e4` and then finally the node `h7` which contains the real content-store identifier for the resource.

There can be many different types of indexes (static index key length, file-system-like, ...) and those should be implemented as we need them. For starters, this task requires that at least the `static index key length` indexer be implemented.

## Work Items

- [X] Implement the `StaticIndexer` which indexes resources by key of a known and static size.
- [X] Implement the tree structure.
- [X] Implement search, range search, addition, update and removal of leaf nodes.
- [ ] Implement a high-level interface to interact with the content-store indexes.
