### ISSUE TITLE
OpenAPI code generation Framework

### ISSUE THREAD

**Issue by tltran-legion** [legion-labs/legion#1529]
# Summary

In the context of migrating from gRPC to Rest APIs a code generation framework is needed.
It should be able to generate Rust code for both client and server sides based on an OpenAPI v3 specification.

# Subtasks
- [x] Analyze and compare the different existing framework
- [x] Present to development team the analysis and the framework chosen.
- [x] As a first step we need to decide what template engine and web framework we want to use in the generation.
- [x] Generate all models from the spec.
- [x] Generate a trait with all routes from the spec.
- [x] Generate a server library implementing the API.
- [x] Generate a client library implementing the API.
- [x] Forward query to API implementation for authorization access.
- [x] Handle non json requests and responses

# Nice to have
- [ ] Generate observability elements (logs, traces, metrics ?).
- [ ] Support for other languages (Python ?, Typescript ?).

Details: https://hackmd.io/5hQV4OK8QpGzQnDQqrYNqQ
