### ISSUE TITLE
Prepare AWS Governance environment + Migration of Github runner and ECR to it

### ISSUE THREAD

**Issue by tltran-legion** [legion-labs/legion#1530]
## Summary
We need a  centralized account for shared services like build services, monitoring services, legionlabs AMI, Container Images Registry.

## Current State
Currently, we are using legionlabs-playground's account to host services such as build machines, AMI, Container Images, engine services.  legionlabs-playground, should only be use for exploration and experimentation purpose.  It should not host services and data that are stable and that will be used by other accounts.

## Tasks

- [x] Create governance aws account under our AWS organization
- [x] Create a VPC in ca-central-1
- [x] Create the github workflow to use governance account for the creation of AMI
- [x] Automate the creation of accesses authorization to the AMI from other aws accounts
- [x] Setup github-runners on the governance account.
- [x] Upgrade to the new version of github-runners.
- [x] Update the configuration of build process to deploy legion labs images to ECR of governance env.
- [x] Automate the creation of accesses authorization to the images repositories from the other aws accounts.
- [ ] Update the images endpoints on services deployment.

## DoD
- [x] Feature has been deployed and tested on UAT.
- [ ] Feature has been documented.
