### ISSUE TITLE
Multi-regions EKS cluster

### ISSUE THREAD

**Issue by tltran-legion** [legion-labs/legion#1533]
## Summary
We need to have a possibility to spawn an editor/runtime server in another region than ca-central-1.
The goal is to define an architecture for the infrastructure that provide the possibility to host EKS nodes in multiple region to to provide maximum fault tolerance but more importantly less latency as possible between Client (Editor) and Server (Editor/Runtime).

## Current State
Actual infrastructure is only deployed in ca-central-1, with only one EKS cluster.

# Work Items
- [ ] Read the documentation these articles: [1](https://blogs.mulesoft.com/dev-guides/how-to-tutorials/multi-region-deployments-on-eks/) [2](https://disaster-recovery.workshop.aws/en/services/containers/eks/eks-cluster-multi-region.html), [3](https://aws.amazon.com/blogs/containers/operating-a-multi-regional-stateless-application-using-amazon-eks/).
- [ ] Pros, cons of possible slutions and present the final chosen solution.
- [ ] Implement the solution.
