### ISSUE TITLE
Prepare AWS UAT environment + Migration of existing service to it

### ISSUE THREAD

**Issue by tltran-legion** [legion-labs/legion#1534]
# Summary

To provide a more testable environment to our 'Qa', we need to create a new AWS environment with limited access.  The User Acceptance Test (UAT) environment should:
- only contains services that are ready to be tested.
- be monitored and kept up and running during most of the time.
- follow a defined deployment process including version of services and data deployed.

# Current State
The actual environment use by Legion Labs's team is playground.  The playground environment is actually not adapted to testing and stabilization purpose.  Playground has been created with exploration goal in mind, but have been used for multiple other purposes: testing, provisioning build machines, storing AMI, container images and so on...  The UAT environment will be the first step to be prepared for the live.  

# Subtasks
- [x] Create subaccount that belong to organizations and assign proper accesses right to the different users groups. 
- [x] Create VPC
- [x] Create DNS record for API on UAT environment
- [x] Create empty EKS cluster
- [x] Create ingress
- [x] Integrate cognito authentication (pool + admin portal client app)
- [x] Create ECR permissions for cross-acccount access.
- [x] Create AMI permissions for cross-account access.
- [x] Integrate into the EKS cluster the services that are actually in playground
- [ ] Remove/clean-up old EKS cluster & other resources from playground.
