### ISSUE TITLE
Protection of Personal Information

### ISSUE THREAD

**Issue by tltran-legion** [legion-labs/legion#1535]
Thanh Liem Tran

## Summary
The goal is to understand company responsibilities and prepare questions for lawyer regarding Personal Protection Information laws (Quebec, Canada, GDPR,...)

## Current State
Currently, we have multiple data stored within our system but we have not identified what, where, how and by whom are the data accessible.

## Tasks
- [x] Read and understanding the company responsibilities in regard of PPI
- [x] Prepare first draft of documentation to present to team.
- [ ] Meet with lawyer to present our finding and ask questions.
