### ISSUE TITLE
Define issues/projects/milestones workflows

### ISSUE THREAD

**Issue by jelmansouri** [legion-labs/legion#1543]
## Summary

As we are heading toward M3 our open source milestone, we should start setting normalize our issues, projects handling.
One suggestion would be to have a project per sprint. and a project per milestone.
The sprint project would track tasks.
The milestone project would contains everything set to the milestone.
We need to create a milestone in GitHub to do so, see: https://github.com/legion-labs/legion/milestones/new

## Current State

We introduced templates for issues, but they might need tweaks/improvements.

## Work Items

- [x] Propose labels format
- [x] Try sprint project
- [x] Try milestone project to see if it's required, maybe combine with mega backlog
