### ISSUE TITLE
Overhaul load state machine

### ISSUE THREAD

**Issue by ndubois-legion** [legion-labs/legion#1567]
## Summary
Leaner API & make loading steps more configurable per type

## Current State
Currently, loading is klunkly. APIs should probably have a single entry point for accessing resources, in both offline & runtime. We should also have a way for defining the loading graph per resource type, or just per resource.
Use Reference<T> in the APIs, and avoid the mix of Handle<T>, HandleUntyped, ReferenceUntype. Are those really useful?

## Tasks
- [x] Remove all the AssetRegistry::loadXXX() APIs and keep a single async one.
- [x] Remove the loading thread
- [x] Implement entity
- [x] Implement an example, like shader and texture
- [ ] Review API with Rendering team
...
