### ISSUE TITLE
Blender plugin for Legion Engine

### ISSUE THREAD

**Issue by kirdaybov** [legion-labs/legion#1623]
## Summary
We want to be able to connect to the Legion Engine from Blender and pull/push meshes, materials, animations between. The blender scene shouldn't be stored on the user machine but on the server.

## Current State
At the moment we import the data into the engine by using zipped GLTF file folder.

## Tasks
- [x] Implement Blender plugin and establish the connection to the engine.
- [x] Import data into the engine directly from Blender.
- [x] Protocols for reimport: request available gltf files, request specific gltf.
- [x] UI for pulling the data from the engine and allow selecting the data to import in the engine.
- [ ] Reimport modified data in the engine
- [ ] Implement plugin packager to remove the dependency from the repo
