### ISSUE TITLE
Bridge gap between property grid requirement and UX/UI V0

### ISSUE THREAD

**Issue by alexandra-nemery** [legion-labs/legion#1690]
## Summary
As a user, I want a proper experience with the property grid

## Current State
Currently, some feature are missing

## Tasks
- [ ] Define feature set
- [ ] Recursiveness
- [ ] #1735
- [x] #1691
- [ ] Textbox and Textarea
- [x] Optional properties
   - [x] Option of component
   - [x] Option of vectors
- [ ] Vectors (array of properties)
  - [ ] Vector of component
  - [ ] Vector of option (of vector of component, you get it 😋 )
- [ ] Enum
- [x] Component (with select + modal/dialog?)
