### ISSUE TITLE
Analyze the workings of the Kruger engine, using the sample character animation data that has been produced (~10d)

### ISSUE THREAD

**Issue by ndubois-legion** [legion-labs/legion#1730]
## Summary
Analyze Kruger engine, more specifically the animation system 

## Work Items
- [x] Analyze engine and animation system with sample character animation data
- [x] Create architectural skeleton of the animation system in Legion
- [x] Create timeline and tick the key frames
- [x] Apply animation every key frame
