### ISSUE TITLE
Check if we can pull on resources in runtime-srv

### ISSUE THREAD

**Issue by aganea** [legion-labs/legion#1746]
## Summary
See what it takes for the runtime-srv to build on demand through the BuildDevice instead of using the manifest.

## Current State
Currently, we are using building the data (I think) in the editor and providing a game.manifest for loading in runtime-srv. Check if we can run the runtime without the manifest, but just the "world" entity ResourceId.

## Work Items
- [x] See if possible to run the Pong demo
- [x] Fix panic when project-path directory does not exist in full
- [ ] Remove the manifest
