### ISSUE TITLE
Demo scene

### ISSUE THREAD

**Issue by vduboisdendien-legion** [legion-labs/legion#1781]
## Summary
Make sure we can import a demo scene

## Current State
Currently we don't have a way to easily import large scenes with a lot of instanced meshes.
Pain points are:
- Currently we don't derive entities from GLTF.
- GltfFile is very slow to parse so the iteration time is bad. Maybe introduce a separate parsed GLTF resource.
- Texture are compiled into unnecessary formats which makes compilation even longer.
- Dependency managing is tricky. We have to fill GltfLoader on assignation.
- Assigning entities derived from Gltf is tricky because of the mangled names.

## Work Items

- [x] gltf2entities compiler
- [x] Hack assigning of the root entity to the children of the entity that we dragndrop a .gltf resource onto
- [ ] Split parsed GLTF
- [ ] Pass texture compilation information
