### ISSUE TITLE
Code Generation for Python language

### ISSUE THREAD

**Issue by tltran-legion** [legion-labs/legion#1795]
## Summary
Being able to use the Code generation framework to generate Client/Server code in Python.

## Current State

The Code generation framework is now only generating Client/Servers code in Rust. We need to be able to support multiple languages such as Python, Typescript....  This issue will be focusing on generating code to support Python language.
## Tasks
- [x] Add a basic python generator to the lgn-api-codegen crate.
- [x] Generate python models based on the open api schemas
- [x] Generate parameters and responses classes.
- [x] Generate a client library corresponding to the Api.
