### ISSUE TITLE
Layout V1

### ISSUE THREAD

**Issue by timnitsas-legion** [legion-labs/legion#1855]
## Summary
Update the Layout following review feedback

## Work Items
- [ ] Use css variables for `lm_goldenlayout` (and find a color that works)
- [ ] `RootContext.getLayout()` should be constrained with types allowing to centralize the definition of components, and have type safety (use .d.ts ? use a layout file ?)
- [ ] `Layout.addComponent()` should use stores for adding a component
- [ ] `LayoutComponents` could be a `Map<symbol, object>` as long as it fits the singleton and singleton-by-id behaviour
- [ ] Serialize layout
- [ ] Add a load icon inside the tabs

https://github.com/legion-labs/legion/pull/1829/files/69b6410d39355ad70bdf952ea1b902ae132ed990
