### ISSUE TITLE
OpenAPI: Codegen improvements

### ISSUE THREAD

**Issue by ademange-legion** [legion-labs/legion#1905]
## Summary

Improve the openapi codegen to better support our needs.

## Work Items
- [x] Ability to serve multiple APIs in a single HTTP server.
- [x] Regroup request arguments in a dedicated type to better support defaults.
- [x] Replace reqwest by hyper client library for better access to HTTP Parts
- [x] Add mutable Context arg to access / edit request and response infos
- [x] Add axum ConnectInfo extractor
- [x] Add codegen test crate to validate compilation
