### ISSUE TITLE
Animation graph v1

### ISSUE THREAD

**Issue by florenceCloutier** [legion-labs/legion#1915]
## Summary
Describe the structure of the animation graph and add some logic.

## Current State
Currently, ready for review.

## Work Items
- [x] Add structure of the anim graph in legion based on the graph in KRG engine
- [x] Add support for different nodes (state machine node, animation clip node, etc.)
- [x] Add logic to the anim graph (transitions between nodes (edges) and conditions for transitions)
- [x] Integrate use of animation skeleton in the graph
