### ISSUE TITLE
Migrate content store service

### ISSUE THREAD

**Issue by tltran-legion** [legion-labs/legion#1974]
## Summary
Goal is to migrate the `Content Store` service to OpenAPI using the Code Generation framework.

## Current State

At the moment, the `Content Store` service is using gRPC we need it to follow the defined new API convention.
## Work Items
- [x] Using the Code Generation Framework to generate the service skeleton.
- [x] Port of the actual business logic of the service into the new skeleton.
- [x] Improve the generated codegen client to support authentication.
- [x] Reuse the common types from the API with the governance service.
