### ISSUE TITLE
Authentication with Cognito for multiple applications on multiple environment.

### ISSUE THREAD

**Issue by tltran-legion** [legion-labs/legion#2003]
## Summary

Create a Cognito User pool under legionengine.com and define the mechanism of creating application client to access to the user pool.

## Current State

Cognito pool (legionlabs.com) user pool is created in playground aws account and it is use to serve authentication for client -applications that are hosted on playground (analytics and editor). 
The call back are urls are on httsp://editor.legionlabs.com for the Editor and https://analytics.legionlabs.com for Analytics which are normally for Live Environment.   Since we only have now multiple environments for multiple apps we need to be able define another way on a more stable environment.

Details: https://hackmd.io/Kx7fShQqQN-Vi9yyXdDi7w?view

## Work Items

- [x] Terraform another user pool under legionengine.com
- [x] Create the new App Client under the new user pool.
- [x] Create and Associate a new Azure Identity provider.
- [x] Update the Web apps to use the new App Client.
