### ISSUE TITLE
Animation - Third person controller 

### ISSUE THREAD

**Issue by florenceCloutier** [legion-labs/legion#2084]
## Summary
Add support for third person controller in the animation system.

## Current State
Currently, 

## Work Items
- [x] Add support for keyboard event inputs
- [x] Add an event condition node that changes states on keyboard input
- [ ] Add root motion for the skeleton to move around

**Comment by florenceCloutier** [comment]
## Summary
Add support for third person controller in the animation system.

## Current State
Currently, 

## Work Items
- [] Add support for keyboard event inputs
- [] Add an event condition node that changes states on keyboard input
