### ISSUE TITLE
Shared and incremental source indexing

### ISSUE THREAD

**Issue by ndubois-legion** [legion-labs/legion#713]
## Objective

Index is used to describe the dependencies between resources. It will eventually be used to query the content of the Source Control. Current indexing is local, not incremental nor scalable. This epic's objective is to be more efficient on the index computing, so we can **share** already computed sub indices and we could **incrementally update** parts of it.

## Task breakdown
- [x] first pass of source control integration
- [x] provide workspace folder checksum from source control
- [x] cache source.index in temp/ under source control dir checksum
- [x] recursively build directory-based sub-indices
- [ ] .meta cleanup
  - [ ] replace 'checksum' with source control based checksum
  - [ ] remove 'dependencies' in favor of computing them when building (sub-)index
- [x] second pass source-control integration (commit, checkout, ...)
- [x] stretch goal: remove sample-data temp/ from git
